import { NextResponse } from 'next/server';

const projects = [
  {
    id: '1',
    client: 'CLAWWORK',
    title: 'AI Economic Agent',
    category: 'Autonomous AI Systems',
    image: '/images/3d-ai-agent.webp',
    color: '#00FF88',
    description: 'Autonomous AI coworker that completes real-world professional tasks, earns income, and manages its own token budget to stay solvent.',
    tech: ['Python', 'Claude API', 'LangChain', 'Multi-Agent'],
    year: '2025',
  },
  {
    id: '2',
    client: 'CLIENTGUARD',
    title: 'Fraud Detection AI',
    category: 'AI · FinTech · Insurance',
    image: '/images/3d-fraud-detection.webp',
    color: '#3B82F6',
    description: 'AI-powered fraud detection platform helping insurance companies save $500K–2M annually with 90%+ accuracy.',
    tech: ['Next.js', 'Prisma', 'PostgreSQL', 'ML/AI'],
    year: '2025',
  },
  {
    id: '3',
    client: 'FLOC',
    title: 'Hyperlocal Nightlife',
    category: 'Mobile · Social Discovery',
    image: '/images/3d-nightlife.webp',
    color: '#A855F7',
    description: 'Feel where your people go. Discover bars, events, and see where your contacts are going out tonight.',
    tech: ['React Native', 'Node.js', 'Maps API', 'PostgreSQL'],
    year: '2025',
  },
  {
    id: '4',
    client: 'COMMANDCENTER',
    title: 'Unified Ops Dashboard',
    category: 'SaaS · Developer Tools',
    image: '/images/3d-ops-dashboard.webp',
    color: '#F59E0B',
    description: 'One pane of glass — Vercel deploys, analytics, Stripe revenue, and email campaigns unified.',
    tech: ['Next.js', 'Vercel API', 'Stripe', 'Resend'],
    year: '2024',
  },
  {
    id: '5',
    client: 'SNEAKX',
    title: 'The Sneaker Exchange',
    category: 'Marketplace · Trading',
    image: '/images/3d-sneaker-exchange.webp',
    color: '#CCFF00',
    description: 'Neo-brutalist sneaker trading platform. Live tickers, authentication tags, real-time bids.',
    tech: ['React', 'Node.js', 'WebSockets', 'Drizzle ORM'],
    year: '2025',
  },
  {
    id: '6',
    client: 'NAVIGATOR',
    title: 'AI Onboarding Platform',
    category: 'HR Tech · AI Agents',
    image: '/images/3d-onboarding-platform.webp',
    color: '#10B981',
    description: 'AI agent-powered onboarding that adapts to each new hire and automates the workflow from day one.',
    tech: ['Next.js', 'AI Agents', 'SQLite', 'TypeScript'],
    year: '2024',
  },
  {
    id: '7',
    client: 'GLOWMARK',
    title: 'Content Protection Suite',
    category: 'Security · Creative Tools',
    image: '/images/3d-content-protection.webp',
    color: '#EC4899',
    description: 'Watermark and protect content with visible marks, invisible encoding, and cryptographic signing.',
    tech: ['Next.js', 'Canvas API', 'Crypto', 'Vercel'],
    year: '2025',
  },
  {
    id: '8',
    client: 'ANTIGRAVITY',
    title: 'Agent Swarm Engine',
    category: 'AI Infrastructure',
    image: '/images/3d-agent-swarm.webp',
    color: '#6366F1',
    description: 'Deploy autonomous Gemini-powered agent swarms. Orchestrate specialized AI teams at scale.',
    tech: ['Python', 'Gemini API', 'Multi-Agent', 'YAML'],
    year: '2025',
  },
  {
    id: '9',
    client: 'WHISTLEBLOW',
    title: 'E-Commerce Arbitrage',
    category: 'Automation · eCommerce',
    image: '/images/3d-ecommerce-arbitrage.webp',
    color: '#14B8A6',
    description: 'Automated arbitrage engine that scans marketplaces and executes cross-platform trades.',
    tech: ['Node.js', 'Puppeteer', 'Redis', 'Docker'],
    year: '2024',
  },
  {
    id: '10',
    client: 'TRADINGWATCHER',
    title: 'Market Signal Tracker',
    category: 'FinTech · Data',
    image: '/images/3d-market-signal.webp',
    color: '#F97316',
    description: 'Real-time market signal tracker with custom alerts and pattern detection for serious traders.',
    tech: ['Next.js', 'WebSockets', 'Charts', 'PostgreSQL'],
    year: '2024',
  },
];

export async function GET() {
  return NextResponse.json(projects);
}
